# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_gibbs_lm <- function(y, X, iter = 2L, initphi = 5, hyp_phi_alph = 5, hyp_phi_gam = 8) {
    .Call(`_gibby_rcpp_gibbs_lm`, y, X, iter, initphi, hyp_phi_alph, hyp_phi_gam)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_gibby_mvrnormArma`, n, mu, sigma)
}

mygamma <- function(n = 10L, a_shape = 1, b_rate = 1) {
    .Call(`_gibby_mygamma`, n, a_shape, b_rate)
}

myinvgamma <- function(n = 10L, a_shape = 1, b_rate = 1) {
    .Call(`_gibby_myinvgamma`, n, a_shape, b_rate)
}

rcpp_gibbs_logistic <- function(y, X, sigma, iter = 2L) {
    .Call(`_gibby_rcpp_gibbs_logistic`, y, X, sigma, iter)
}

rcpp_rpg <- function(b, c) {
    .Call(`_gibby_rcpp_rpg`, b, c)
}

rcpp_gibbs_probit <- function(y, X, iter = 2L) {
    .Call(`_gibby_rcpp_gibbs_probit`, y, X, iter)
}

